name: Deploy Web Stable

on:
  workflow_run:
    workflows: ["CI/CD"]
    types: [completed]
    branches: [stable]

env:
  FLUTTER_VERSION: "3.27.1"

jobs:
  deploy-web-stable:
    name: Deploy Web Stable
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'stable'
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-web-stable
      cancel-in-progress: true
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TYPESYNCED }}
          projectId: typesynced
          channelId: live
